### ISSUE TITLE
sql file?

### ISSUE THREAD

**Issue by jackttcoms** [crjoseabraham/shoppingcart#1]
Hi please can i have the sql file? Thanks... amazing git

**Comment by crjoseabraham** [comment]
Hi! I just added the .sql file to the data/ folder and updated the README file to put some credentials you can use to log in. Backend functions are working fine but I haven't touched UI yet so it is still plain HTML. Thank you for passing by.

**Comment by jackttcoms** [comment]
Wow. thanks so much. Great work.

One potential suggestion: add a secure user management func (login, register, forgot, verify etc.)

Thanks again
